In [83]:
import numpy as np
import pandas as pd

In [84]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score

In [85]:
dataset_train = pd.read_csv(r"C:\Users\DELL\Downloads\Engine Failure Prediction\PM_train.txt")

In [86]:
dataset_test = pd.read_csv(r"C:\Users\DELL\Downloads\Engine Failure Prediction\PM_test.txt")

In [87]:
dataset_truth = pd.read_csv(r"C:\Users\DELL\Downloads\Engine Failure Prediction\PM_truth.txt")

In [88]:
dataset_train.head()

1 1 -0.0007 -0.0004 100.0 518.67 641.82 1589.70 1400.60 14.62 21.61 554.36 2388.06 9046.19 1.30 47.47 521.66 2388.02 8138.62 8.4195 0.03 392 2388 100.00 39.06 23.4190  
0  1 2 0.0019 -0.0003 100.0 518.67 642.15 1591.82...                                                                                                                      
1  1 3 -0.0043 0.0003 100.0 518.67 642.35 1587.99...                                                                                                                      
2  1 4 0.0007 0.0000 100.0 518.67 642.35 1582.79 ...                                                                                                                      
3  1 5 -0.0019 -0.0002 100.0 518.67 642.37 1582.8...                                                                                                                      
4  1 6 -0.0043 -0.0001 100.0 518.67 642.10 1584.4...

In [89]:
dataset_test.head()

1 1 0.0023 0.0003 100.0 518.67 643.02 1585.29 1398.21 14.62 21.61 553.90 2388.04 9050.17 1.30 47.20 521.72 2388.03 8125.55 8.4052 0.03 392 2388 100.00 38.86 23.3735  
0  1 2 -0.0027 -0.0003 100.0 518.67 641.71 1588.4...                                                                                                                    
1  1 3 0.0003 0.0001 100.0 518.67 642.46 1586.94 ...                                                                                                                    
2  1 4 0.0042 0.0000 100.0 518.67 642.44 1584.12 ...                                                                                                                    
3  1 5 0.0014 0.0000 100.0 518.67 642.51 1587.19 ...                                                                                                                    
4  1 6 0.0012 0.0003 100.0 518.67 642.11 1579.12 ...

In [90]:
dataset_truth.head()

112 
0    98
1    69
2    82
3    91
4    93

In [91]:
dataset_train.isnull().any()

1 1 -0.0007 -0.0004 100.0 518.67 641.82 1589.70 1400.60 14.62 21.61 554.36 2388.06 9046.19 1.30 47.47 521.66 2388.02 8138.62 8.4195 0.03 392 2388 100.00 39.06 23.4190      False
dtype: bool

In [92]:
dataset_test.isnull().any()

1 1 0.0023 0.0003 100.0 518.67 643.02 1585.29 1398.21 14.62 21.61 553.90 2388.04 9050.17 1.30 47.20 521.72 2388.03 8125.55 8.4052 0.03 392 2388 100.00 38.86 23.3735      False
dtype: bool

In [93]:
dataset_truth.isnull().any()

112     False
dtype: bool

In [94]:
dataset_test = pd.read_csv(r'C:\Users\DELL\Downloads\Engine Failure Prediction\PM_test.txt',sep = ' ',header=None).drop([26,27],axis =1)
col_names = ['id','cycle','selling1','selling2','selling3','s1','s2','s3','s4','s5','s6','s7','s8','s9','s10','s11','s12','s13','s14','s15','s16','s17','s18','s19','s20','s21']
dataset_test.columns=col_names
print('Shape of Test dataset' ,dataset_test.shape)
dataset_test.head()

Shape of Test dataset (13096, 26)


id  cycle  selling1  selling2  selling3      s1      s2       s3       s4  \
0   1      1    0.0023    0.0003     100.0  518.67  643.02  1585.29  1398.21   
1   1      2   -0.0027   -0.0003     100.0  518.67  641.71  1588.45  1395.42   
2   1      3    0.0003    0.0001     100.0  518.67  642.46  1586.94  1401.34   
3   1      4    0.0042    0.0000     100.0  518.67  642.44  1584.12  1406.42   
4   1      5    0.0014    0.0000     100.0  518.67  642.51  1587.19  1401.92   

      s5  ...     s12      s13      s14     s15   s16  s17   s18    s19  \
0  14.62  ...  521.72  2388.03  8125.55  8.4052  0.03  392  2388  100.0   
1  14.62  ...  522.16  2388.06  8139.62  8.3803  0.03  393  2388  100.0   
2  14.62  ...  521.97  2388.03  8130.10  8.4441  0.03  393  2388  100.0   
3  14.62  ...  521.38  2388.05  8132.90  8.3917  0.03  391  2388  100.0   
4  14.62  ...  522.15  2388.03  8129.54  8.4031  0.03  390  2388  100.0   

     s20      s21  
0  38.86  23.3735  
1  39.02  23.3916  
2  39.08  23.4166  
3  39.00  23.3737  
4  38.99  23.4130  

[5 rows x 26 columns]

In [95]:
dataset_train = pd.read_csv(r'C:\Users\DELL\Downloads\Engine Failure Prediction\PM_train.txt',sep = ' ',header=None).drop([26,27],axis=1)
dataset_train.columns = col_names
print('Shape of Train dataset' ,dataset_train.shape)
dataset_train.head()

Shape of Train dataset (20631, 26)


id  cycle  selling1  selling2  selling3      s1      s2       s3       s4  \
0   1      1   -0.0007   -0.0004     100.0  518.67  641.82  1589.70  1400.60   
1   1      2    0.0019   -0.0003     100.0  518.67  642.15  1591.82  1403.14   
2   1      3   -0.0043    0.0003     100.0  518.67  642.35  1587.99  1404.20   
3   1      4    0.0007    0.0000     100.0  518.67  642.35  1582.79  1401.87   
4   1      5   -0.0019   -0.0002     100.0  518.67  642.37  1582.85  1406.22   

      s5  ...     s12      s13      s14     s15   s16  s17   s18    s19  \
0  14.62  ...  521.66  2388.02  8138.62  8.4195  0.03  392  2388  100.0   
1  14.62  ...  522.28  2388.07  8131.49  8.4318  0.03  392  2388  100.0   
2  14.62  ...  522.42  2388.03  8133.23  8.4178  0.03  390  2388  100.0   
3  14.62  ...  522.86  2388.08  8133.83  8.3682  0.03  392  2388  100.0   
4  14.62  ...  522.19  2388.04  8133.80  8.4294  0.03  393  2388  100.0   

     s20      s21  
0  39.06  23.4190  
1  39.00  23.4236  
2  38.95  23.3442  
3  38.88  23.3739  
4  38.90  23.4044  

[5 rows x 26 columns]

In [96]:
pm_truth=pd.read_csv(r'C:\Users\DELL\Downloads\Engine Failure Prediction\PM_truth.txt',sep = ' ',header = None).drop([1],axis=1)
pm_truth.columns=['more']
pm_truth['id']=pm_truth.index+1
pm_truth.head()

more  id
0   112   1
1    98   2
2    69   3
3    82   4
4    91   5

In [97]:
rul = pd.DataFrame(dataset_test.groupby('id')['cycle'].max()).reset_index()
rul.columns = ['id','max']
rul.head()

id  max
0   1   31
1   2   49
2   3  126
3   4  106
4   5   98

In [98]:
pm_truth['rtf']= pm_truth['more']+rul['max']
pm_truth.head()

more  id  rtf
0   112   1  143
1    98   2  147
2    69   3  195
3    82   4  188
4    91   5  189

In [99]:
pm_truth.drop('more',axis = 1,inplace = True)
dataset_test = dataset_test.merge(pm_truth,on=['id'],how = 'left')
dataset_test['ttf']=dataset_test['rtf'] - dataset_test['cycle']
dataset_test.drop('rtf',axis = 1,inplace = True)
dataset_test.head()

id  cycle  selling1  selling2  selling3      s1      s2       s3       s4  \
0   1      1    0.0023    0.0003     100.0  518.67  643.02  1585.29  1398.21   
1   1      2   -0.0027   -0.0003     100.0  518.67  641.71  1588.45  1395.42   
2   1      3    0.0003    0.0001     100.0  518.67  642.46  1586.94  1401.34   
3   1      4    0.0042    0.0000     100.0  518.67  642.44  1584.12  1406.42   
4   1      5    0.0014    0.0000     100.0  518.67  642.51  1587.19  1401.92   

      s5  ...      s13      s14     s15   s16  s17   s18    s19    s20  \
0  14.62  ...  2388.03  8125.55  8.4052  0.03  392  2388  100.0  38.86   
1  14.62  ...  2388.06  8139.62  8.3803  0.03  393  2388  100.0  39.02   
2  14.62  ...  2388.03  8130.10  8.4441  0.03  393  2388  100.0  39.08   
3  14.62  ...  2388.05  8132.90  8.3917  0.03  391  2388  100.0  39.00   
4  14.62  ...  2388.03  8129.54  8.4031  0.03  390  2388  100.0  38.99   

       s21  ttf  
0  23.3735  142  
1  23.3916  141  
2  23.4166  140  
3  23.3737  139  
4  23.4130  138  

[5 rows x 27 columns]

In [100]:
dataset_train['ttf']=dataset_train.groupby(['id'])['cycle'].transform(max)-dataset_train['cycle']
dataset_train.head()

id  cycle  selling1  selling2  selling3      s1      s2       s3       s4  \
0   1      1   -0.0007   -0.0004     100.0  518.67  641.82  1589.70  1400.60   
1   1      2    0.0019   -0.0003     100.0  518.67  642.15  1591.82  1403.14   
2   1      3   -0.0043    0.0003     100.0  518.67  642.35  1587.99  1404.20   
3   1      4    0.0007    0.0000     100.0  518.67  642.35  1582.79  1401.87   
4   1      5   -0.0019   -0.0002     100.0  518.67  642.37  1582.85  1406.22   

      s5  ...      s13      s14     s15   s16  s17   s18    s19    s20  \
0  14.62  ...  2388.02  8138.62  8.4195  0.03  392  2388  100.0  39.06   
1  14.62  ...  2388.07  8131.49  8.4318  0.03  392  2388  100.0  39.00   
2  14.62  ...  2388.03  8133.23  8.4178  0.03  390  2388  100.0  38.95   
3  14.62  ...  2388.08  8133.83  8.3682  0.03  392  2388  100.0  38.88   
4  14.62  ...  2388.04  8133.80  8.4294  0.03  393  2388  100.0  38.90   

       s21  ttf  
0  23.4190  191  
1  23.4236  190  
2  23.3442  189  
3  23.3739  188  
4  23.4044  187  

[5 rows x 27 columns]

In [101]:
df_train = dataset_train.copy()
df_test = dataset_test.copy()
period=30
df_train['label_bc'] = df_train['ttf'].apply(lambda x: 1 if x <= period else 0)
df_test['label_bc'] = df_test['ttf'].apply(lambda x: 1 if x <= period else 0)
df_train.head()

id  cycle  selling1  selling2  selling3      s1      s2       s3       s4  \
0   1      1   -0.0007   -0.0004     100.0  518.67  641.82  1589.70  1400.60   
1   1      2    0.0019   -0.0003     100.0  518.67  642.15  1591.82  1403.14   
2   1      3   -0.0043    0.0003     100.0  518.67  642.35  1587.99  1404.20   
3   1      4    0.0007    0.0000     100.0  518.67  642.35  1582.79  1401.87   
4   1      5   -0.0019   -0.0002     100.0  518.67  642.37  1582.85  1406.22   

      s5  ...      s14     s15   s16  s17   s18    s19    s20      s21  ttf  \
0  14.62  ...  8138.62  8.4195  0.03  392  2388  100.0  39.06  23.4190  191   
1  14.62  ...  8131.49  8.4318  0.03  392  2388  100.0  39.00  23.4236  190   
2  14.62  ...  8133.23  8.4178  0.03  390  2388  100.0  38.95  23.3442  189   
3  14.62  ...  8133.83  8.3682  0.03  392  2388  100.0  38.88  23.3739  188   
4  14.62  ...  8133.80  8.4294  0.03  393  2388  100.0  38.90  23.4044  187   

   label_bc  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 28 columns]

In [102]:
df_train.drop(['ttf'],axis = 1,inplace =True)

In [103]:
df_test.drop(['ttf'],axis = 1,inplace =True)

In [104]:
x_test = df_test.iloc[:,:26].values
y_test = df_test.iloc[:,26].values

In [105]:
x_test = df_test.iloc[:,:26]
x_test.columns

Index(['id', 'cycle', 'selling1', 'selling2', 'selling3', 's1', 's2', 's3',
       's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14',
       's15', 's16', 's17', 's18', 's19', 's20', 's21'],
      dtype='object')

In [106]:
x_test

id  cycle  selling1  selling2  selling3      s1      s2       s3  \
0        1      1    0.0023    0.0003     100.0  518.67  643.02  1585.29   
1        1      2   -0.0027   -0.0003     100.0  518.67  641.71  1588.45   
2        1      3    0.0003    0.0001     100.0  518.67  642.46  1586.94   
3        1      4    0.0042    0.0000     100.0  518.67  642.44  1584.12   
4        1      5    0.0014    0.0000     100.0  518.67  642.51  1587.19   
5        1      6    0.0012    0.0003     100.0  518.67  642.11  1579.12   
6        1      7   -0.0000    0.0002     100.0  518.67  642.11  1583.34   
7        1      8    0.0006   -0.0000     100.0  518.67  642.54  1580.89   
8        1      9   -0.0036    0.0000     100.0  518.67  641.88  1593.29   
9        1     10   -0.0025   -0.0001     100.0  518.67  642.07  1585.25   
10       1     11    0.0007   -0.0004     100.0  518.67  642.04  1581.03   
11       1     12    0.0026    0.0003     100.0  518.67  642.54  1587.43   
12       1     13   -0.0056    0.0003     100.0  518.67  641.94  1589.09   
13       1     14    0.0017   -0.0004     100.0  518.67  642.23  1583.16   
14       1     15   -0.0003   -0.0003     100.0  518.67  642.50  1584.81   
15       1     16   -0.0018    0.0003     100.0  518.67  642.32  1584.51   
16       1     17    0.0014    0.0002     100.0  518.67  642.19  1582.70   
17       1     18    0.0035    0.0001     100.0  518.67  642.59  1586.53   
18       1     19    0.0029    0.0001     100.0  518.67  642.43  1585.58   
19       1     20    0.0011   -0.0001     100.0  518.67  642.61  1587.78   
20       1     21    0.0038   -0.0002     100.0  518.67  642.70  1583.30   
21       1     22    0.0012    0.0001     100.0  518.67  642.45  1582.78   
22       1     23    0.0009   -0.0000     100.0  518.67  642.12  1587.51   
23       1     24   -0.0006   -0.0001     100.0  518.67  642.32  1594.29   
24       1     25    0.0028   -0.0003     100.0  518.67  642.25  1582.43   
25       1     26    0.0047   -0.0005     100.0  518.67  642.48  1583.28   
26       1     27   -0.0007    0.0001     100.0  518.67  642.08  1586.65   
27       1     28    0.0022    0.0005     100.0  518.67  641.93  1594.25   
28       1     29    0.0014    0.0001     100.0  518.67  641.95  1587.15   
29       1     30   -0.0025    0.0004     100.0  518.67  642.79  1585.72   
...    ...    ...       ...       ...       ...     ...     ...      ...   
13066  100    169    0.0026   -0.0000     100.0  518.67  642.36  1591.25   
13067  100    170   -0.0006   -0.0004     100.0  518.67  642.70  1589.92   
13068  100    171   -0.0026   -0.0003     100.0  518.67  642.83  1586.64   
13069  100    172    0.0007    0.0003     100.0  518.67  642.61  1594.51   
13070  100    173   -0.0003   -0.0000     100.0  518.67  642.56  1591.49   
13071  100    174   -0.0005    0.0003     100.0  518.67  642.81  1589.97   
13072  100    175    0.0019    0.0000     100.0  518.67  642.25  1595.08   
13073  100    176    0.0002    0.0002     100.0  518.67  642.73  1590.96   
13074  100    177   -0.0041   -0.0003     100.0  518.67  642.80  1593.26   
13075  100    178    0.0001    0.0005     100.0  518.67  642.32  1591.78   
13076  100    179    0.0041    0.0001     100.0  518.67  642.30  1588.93   
13077  100    180   -0.0004    0.0001     100.0  518.67  642.65  1593.47   
13078  100    181   -0.0010    0.0000     100.0  518.67  642.94  1586.09   
13079  100    182   -0.0027   -0.0001     100.0  518.67  642.28  1598.05   
13080  100    183    0.0009    0.0001     100.0  518.67  642.78  1595.34   
13081  100    184    0.0001   -0.0004     100.0  518.67  642.60  1595.89   
13082  100    185    0.0032    0.0004     100.0  518.67  642.84  1592.18   
13083  100    186   -0.0025    0.0005     100.0  518.67  643.38  1592.04   
13084  100    187    0.0019    0.0002     100.0  518.67  642.40  1595.19   
13085  100    188    0.0010    0.0005     100.0  518.67  643.35  1589.88   
13086  100    189   -0.0003    0.0002     100.0  518.67 

In [107]:
y_test

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [108]:
x_train = df_train.iloc[:,:-1].values
y_train = df_train.iloc[:,-1:].values

In [109]:
x_train

array([[ 1.00000e+00,  1.00000e+00, -7.00000e-04, ...,  1.00000e+02,
         3.90600e+01,  2.34190e+01],
       [ 1.00000e+00,  2.00000e+00,  1.90000e-03, ...,  1.00000e+02,
         3.90000e+01,  2.34236e+01],
       [ 1.00000e+00,  3.00000e+00, -4.30000e-03, ...,  1.00000e+02,
         3.89500e+01,  2.33442e+01],
       ...,
       [ 1.00000e+02,  1.98000e+02,  4.00000e-04, ...,  1.00000e+02,
         3.84400e+01,  2.29333e+01],
       [ 1.00000e+02,  1.99000e+02, -1.10000e-03, ...,  1.00000e+02,
         3.82900e+01,  2.30640e+01],
       [ 1.00000e+02,  2.00000e+02, -3.20000e-03, ...,  1.00000e+02,
         3.83700e+01,  2.30522e+01]])

In [110]:
y_train

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [111]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [112]:
ypred = model.predict(x_test)

In [113]:
ypred

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [114]:
from sklearn.metrics import accuracy_score
accuracy_score(ypred,y_test)

0.9843463653023824

In [115]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(ypred,y_test)
cm1

array([[12720,   161],
       [   44,   171]], dtype=int64)

In [116]:
import joblib

In [117]:
joblib.dump(model,"engine_model.sav")

['engine_model.sav']